import type { SearchResultItem } from './types';

export const MOCK_SEARCH_RESULTS: SearchResultItem[] = [
  {
    id: 'search-1',
    name: '벨로테로 가나디',
    quantity: 543,
    category: '필러/보톡스/실',
    recentInboundDate: '2025.08.08',
    expirationDate: '25.01.01',
    isFavorite: false,
  },
  {
    id: 'search-2',
    name: '벨로테로 나바바바바',
    quantity: 234,
    category: '소모품',
    recentInboundDate: '2025.07.15',
    expirationDate: '25.03.20',
    isFavorite: true,
  },
  {
    id: 'search-3',
    name: '벨로테로 두루두루',
    quantity: 876,
    category: '필러/보톡스/실',
    recentInboundDate: '2025.08.10',
    expirationDate: '25.02.15',
    isFavorite: false,
  },
  {
    id: 'search-4',
    name: '벨로테로 베로베로',
    quantity: 321,
    category: '화장품',
    recentInboundDate: '2025.06.20',
    expirationDate: '25.04.10',
    isFavorite: false,
  },
  {
    id: 'search-5',
    name: '벨로테로 사사사사',
    quantity: 654,
    category: '주사제',
    recentInboundDate: '2025.08.05',
    expirationDate: '25.01.30',
    isFavorite: true,
  },
  {
    id: 'search-6',
    name: '벨로테로 아아라아라',
    quantity: 432,
    category: '필러/보톡스/실',
    recentInboundDate: '2025.07.28',
    expirationDate: '25.03.05',
    isFavorite: true,
  },
  {
    id: 'search-7',
    name: '벨로테로 아아아아라',
    quantity: 789,
    category: '소모품',
    recentInboundDate: '2025.08.12',
    expirationDate: '25.02.28',
    isFavorite: false,
  },
  {
    id: 'search-8',
    name: '벨로테로 하하하하하',
    quantity: 156,
    category: '화장품',
    recentInboundDate: '2025.06.30',
    expirationDate: '25.05.15',
    isFavorite: false,
  },
  {
    id: 'search-9',
    name: '주사제 A형',
    quantity: 987,
    category: '주사제',
    recentInboundDate: '2025.08.01',
    expirationDate: '25.01.20',
    isFavorite: true,
  },
  {
    id: 'search-10',
    name: '주사제 B형',
    quantity: 543,
    category: '필러/보톡스/실',
    recentInboundDate: '2025.07.10',
    expirationDate: '25.03.30',
    isFavorite: false,
  },
  {
    id: 'search-11',
    name: '주사제 C형',
    quantity: 234,
    category: '소모품',
    recentInboundDate: '2025.08.15',
    expirationDate: '25.02.10',
    isFavorite: true,
  },
  {
    id: 'search-12',
    name: '소모품 마스크',
    quantity: 1200,
    category: '소모품',
    recentInboundDate: '2025.08.08',
    expirationDate: '25.12.31',
    isFavorite: false,
  },
  {
    id: 'search-13',
    name: '소모품 장갑',
    quantity: 2500,
    category: '주사제',
    recentInboundDate: '2025.08.05',
    expirationDate: '25.12.31',
    isFavorite: true,
  },
  {
    id: 'search-14',
    name: '소모품 주사기',
    quantity: 800,
    category: '화장품',
    recentInboundDate: '2025.07.20',
    expirationDate: '25.11.30',
    isFavorite: false,
  },
  {
    id: 'search-15',
    name: '필러 주사제',
    quantity: 456,
    category: '주사제',
    recentInboundDate: '2025.08.10',
    expirationDate: '25.04.20',
    isFavorite: true,
  },
  {
    id: 'search-16',
    name: '필러 보톡스',
    quantity: 678,
    category: '필러/보톡스/실',
    recentInboundDate: '2025.07.25',
    expirationDate: '25.05.10',
    isFavorite: false,
  },
  {
    id: 'search-17',
    name: '필러 실',
    quantity: 345,
    category: '필러/보톡스/실',
    recentInboundDate: '2025.08.12',
    expirationDate: '25.06.15',
    isFavorite: true,
  },
  {
    id: 'search-18',
    name: '화장품 크림',
    quantity: 567,
    category: '화장품',
    recentInboundDate: '2025.06.15',
    expirationDate: '25.08.20',
    isFavorite: false,
  },
  {
    id: 'search-19',
    name: '화장품 세럼',
    quantity: 432,
    category: '화장품',
    recentInboundDate: '2025.07.30',
    expirationDate: '25.09.10',
    isFavorite: true,
  },
  {
    id: 'search-20',
    name: '화장품 토너',
    quantity: 789,
    category: '화장품',
    recentInboundDate: '2025.08.05',
    expirationDate: '25.10.05',
    isFavorite: false,
  },
  {
    id: 'search-21',
    name: '주사제 디스포',
    quantity: 234,
    category: '필러/보톡스/실',
    recentInboundDate: '2025.08.08',
    expirationDate: '25.01.15',
    isFavorite: false,
  },
  {
    id: 'search-22',
    name: '주사제 메디',
    quantity: 876,
    category: '화장품',
    recentInboundDate: '2025.07.18',
    expirationDate: '25.02.25',
    isFavorite: true,
  },
  {
    id: 'search-23',
    name: '소모품 거즈',
    quantity: 1500,
    category: '필러/보톡스/실',
    recentInboundDate: '2025.08.01',
    expirationDate: '25.12.31',
    isFavorite: false,
  },
  {
    id: 'search-24',
    name: '소모품 밴드',
    quantity: 2000,
    category: '주사제',
    recentInboundDate: '2025.07.25',
    expirationDate: '25.12.31',
    isFavorite: true,
  },
  {
    id: 'search-25',
    name: '필러 하이알',
    quantity: 321,
    category: '필러/보톡스/실',
    recentInboundDate: '2025.08.10',
    expirationDate: '25.04.30',
    isFavorite: false,
  },
  {
    id: 'search-26',
    name: '필러 주울',
    quantity: 654,
    category: '필러/보톡스/실',
    recentInboundDate: '2025.07.12',
    expirationDate: '25.05.20',
    isFavorite: true,
  },
  {
    id: 'search-27',
    name: '화장품 에센스',
    quantity: 456,
    category: '소모품',
    recentInboundDate: '2025.06.28',
    expirationDate: '25.08.15',
    isFavorite: false,
  },
  {
    id: 'search-28',
    name: '화장품 로션',
    quantity: 567,
    category: '주사제',
    recentInboundDate: '2025.08.03',
    expirationDate: '25.09.25',
    isFavorite: true,
  },
  {
    id: 'search-29',
    name: '주사제 리포',
    quantity: 789,
    category: '소모품',
    recentInboundDate: '2025.08.08',
    expirationDate: '25.01.10',
    isFavorite: false,
  },
  {
    id: 'search-30',
    name: '주사제 뉴필',
    quantity: 432,
    category: '필러/보톡스/실',
    recentInboundDate: '2025.07.22',
    expirationDate: '25.03.15',
    isFavorite: true,
  },
  {
    id: 'search-31',
    name: '주사제 리스타',
    quantity: 567,
    category: '화장품',
    recentInboundDate: '2025.08.14',
    expirationDate: '25.02.20',
    isFavorite: false,
  },
  {
    id: 'search-32',
    name: '주사제 루미',
    quantity: 890,
    category: '소모품',
    recentInboundDate: '2025.07.05',
    expirationDate: '25.04.05',
    isFavorite: true,
  },
  {
    id: 'search-33',
    name: '소모품 멸균솜',
    quantity: 3000,
    category: '소모품',
    recentInboundDate: '2025.08.08',
    expirationDate: '25.12.31',
    isFavorite: false,
  },
  {
    id: 'search-34',
    name: '소모품 알코올',
    quantity: 500,
    category: '주사제',
    recentInboundDate: '2025.08.01',
    expirationDate: '25.11.30',
    isFavorite: true,
  },
  {
    id: 'search-35',
    name: '소모품 바늘',
    quantity: 1500,
    category: '필러/보톡스/실',
    recentInboundDate: '2025.07.28',
    expirationDate: '25.12.15',
    isFavorite: false,
  },
  {
    id: 'search-36',
    name: '소모품 캐뉼라',
    quantity: 800,
    category: '화장품',
    recentInboundDate: '2025.08.10',
    expirationDate: '25.12.20',
    isFavorite: true,
  },
  {
    id: 'search-37',
    name: '필러 레스틸란',
    quantity: 234,
    category: '필러/보톡스/실',
    recentInboundDate: '2025.08.12',
    expirationDate: '25.06.10',
    isFavorite: false,
  },
  {
    id: 'search-38',
    name: '필러 아쿠아필',
    quantity: 456,
    category: '주사제',
    recentInboundDate: '2025.07.20',
    expirationDate: '25.05.25',
    isFavorite: true,
  },
  {
    id: 'search-39',
    name: '필러 테오실',
    quantity: 321,
    category: '소모품',
    recentInboundDate: '2025.08.05',
    expirationDate: '25.07.15',
    isFavorite: false,
  },
  {
    id: 'search-40',
    name: '필러 볼루마',
    quantity: 678,
    category: '화장품',
    recentInboundDate: '2025.07.15',
    expirationDate: '25.08.30',
    isFavorite: true,
  },
  {
    id: 'search-41',
    name: '화장품 마스크팩',
    quantity: 1200,
    category: '화장품',
    recentInboundDate: '2025.08.08',
    expirationDate: '25.10.20',
    isFavorite: false,
  },
  {
    id: 'search-42',
    name: '화장품 클렌징',
    quantity: 654,
    category: '필러/보톡스/실',
    recentInboundDate: '2025.07.25',
    expirationDate: '25.09.15',
    isFavorite: true,
  },
  {
    id: 'search-43',
    name: '화장품 선크림',
    quantity: 432,
    category: '소모품',
    recentInboundDate: '2025.08.12',
    expirationDate: '25.11.10',
    isFavorite: false,
  },
  {
    id: 'search-44',
    name: '화장품 앰플',
    quantity: 789,
    category: '주사제',
    recentInboundDate: '2025.06.30',
    expirationDate: '25.10.05',
    isFavorite: true,
  },
  {
    id: 'search-45',
    name: '주사제 뉴스킨',
    quantity: 345,
    category: '화장품',
    recentInboundDate: '2025.08.15',
    expirationDate: '25.01.25',
    isFavorite: false,
  },
  {
    id: 'search-46',
    name: '주사제 엘라스틴',
    quantity: 567,
    category: '소모품',
    recentInboundDate: '2025.07.10',
    expirationDate: '25.02.28',
    isFavorite: true,
  },
  {
    id: 'search-47',
    name: '소모품 타이어',
    quantity: 200,
    category: '필러/보톡스/실',
    recentInboundDate: '2025.08.01',
    expirationDate: '25.12.31',
    isFavorite: false,
  },
  {
    id: 'search-48',
    name: '소모품 가운',
    quantity: 500,
    category: '주사제',
    recentInboundDate: '2025.08.05',
    expirationDate: '25.12.31',
    isFavorite: true,
  },
  {
    id: 'search-49',
    name: '필러 스컬프트라',
    quantity: 234,
    category: '소모품',
    recentInboundDate: '2025.08.10',
    expirationDate: '25.07.20',
    isFavorite: false,
  },
  {
    id: 'search-50',
    name: '화장품 아이크림',
    quantity: 321,
    category: '필러/보톡스/실',
    recentInboundDate: '2025.07.18',
    expirationDate: '25.09.30',
    isFavorite: true,
  },
  {
    id: 'search-51',
    name: 'Botox Cosmetic',
    quantity: 128,
    category: '필러/보톡스/실',
    recentInboundDate: '2025.08.15',
    expirationDate: '26.02.28',
    isFavorite: false,
  },
  {
    id: 'search-52',
    name: 'Hyaluronic Acid Filler',
    quantity: 256,
    category: '필러/보톡스/실',
    recentInboundDate: '2025.07.22',
    expirationDate: '25.12.15',
    isFavorite: true,
  },
  {
    id: 'search-53',
    name: 'Disposable Syringe',
    quantity: 1024,
    category: '소모품',
    recentInboundDate: '2025.08.01',
    expirationDate: '27.06.30',
    isFavorite: false,
  },
  {
    id: 'search-54',
    name: 'Surgical Gloves',
    quantity: 500,
    category: '소모품',
    recentInboundDate: '2025.07.10',
    expirationDate: '26.05.20',
    isFavorite: true,
  },
  {
    id: 'search-55',
    name: 'Collagen Thread',
    quantity: 89,
    category: '필러/보톡스/실',
    recentInboundDate: '2025.08.20',
    expirationDate: '26.01.10',
    isFavorite: false,
  },
  {
    id: 'search-56',
    name: 'Antioxidant Serum',
    quantity: 342,
    category: '화장품',
    recentInboundDate: '2025.06.25',
    expirationDate: '25.11.30',
    isFavorite: true,
  },
  {
    id: 'search-57',
    name: 'Vitamin C Injection',
    quantity: 156,
    category: '주사제',
    recentInboundDate: '2025.08.12',
    expirationDate: '25.10.15',
    isFavorite: false,
  },
  {
    id: 'search-58',
    name: 'Medical Mask',
    quantity: 2000,
    category: '소모품',
    recentInboundDate: '2025.07.05',
    expirationDate: '27.03.31',
    isFavorite: true,
  },
  {
    id: 'search-59',
    name: 'Dermal Filler',
    quantity: 78,
    category: '필러/보톡스/실',
    recentInboundDate: '2025.08.18',
    expirationDate: '26.03.20',
    isFavorite: false,
  },
  {
    id: 'search-60',
    name: 'Moisturizing Cream',
    quantity: 445,
    category: '화장품',
    recentInboundDate: '2025.06.30',
    expirationDate: '25.12.25',
    isFavorite: true,
  },
  {
    id: 'search-61',
    name: 'Injection Needle',
    quantity: 800,
    category: '소모품',
    recentInboundDate: '2025.08.05',
    expirationDate: '27.01.15',
    isFavorite: false,
  },
  {
    id: 'search-62',
    name: 'PDO Thread',
    quantity: 67,
    category: '필러/보톡스/실',
    recentInboundDate: '2025.08.22',
    expirationDate: '26.04.10',
    isFavorite: true,
  },
  {
    id: 'search-63',
    name: 'Sunscreen Lotion',
    quantity: 523,
    category: '화장품',
    recentInboundDate: '2025.07.12',
    expirationDate: '26.08.30',
    isFavorite: false,
  },
  {
    id: 'search-64',
    name: 'Glutathione Injection',
    quantity: 234,
    category: '주사제',
    recentInboundDate: '2025.08.08',
    expirationDate: '25.11.20',
    isFavorite: true,
  },
  {
    id: 'search-65',
    name: 'Alcohol Swab',
    quantity: 1500,
    category: '소모품',
    recentInboundDate: '2025.07.20',
    expirationDate: '27.05.10',
    isFavorite: false,
  },
  {
    id: 'search-66',
    name: 'Juvederm Ultra',
    quantity: 45,
    category: '필러/보톡스/실',
    recentInboundDate: '2025.08.25',
    expirationDate: '26.02.15',
    isFavorite: true,
  },
  {
    id: 'search-67',
    name: 'Retinol Cream',
    quantity: 389,
    category: '화장품',
    recentInboundDate: '2025.06.18',
    expirationDate: '25.10.30',
    isFavorite: false,
  },
  {
    id: 'search-68',
    name: 'Saline Solution',
    quantity: 678,
    category: '소모품',
    recentInboundDate: '2025.08.03',
    expirationDate: '26.12.31',
    isFavorite: true,
  },
  {
    id: 'search-69',
    name: 'Restylane Filler',
    quantity: 92,
    category: '필러/보톡스/실',
    recentInboundDate: '2025.08.19',
    expirationDate: '26.05.25',
    isFavorite: false,
  },
  {
    id: 'search-70',
    name: 'Niacinamide Serum',
    quantity: 456,
    category: '화장품',
    recentInboundDate: '2025.07.08',
    expirationDate: '26.01.20',
    isFavorite: true,
  },
  {
    id: 'search-71',
    name: 'Lidocaine Injection',
    quantity: 178,
    category: '주사제',
    recentInboundDate: '2025.08.14',
    expirationDate: '25.12.10',
    isFavorite: false,
  },
  {
    id: 'search-72',
    name: 'Cotton Swab',
    quantity: 1200,
    category: '소모품',
    recentInboundDate: '2025.07.25',
    expirationDate: '27.04.15',
    isFavorite: true,
  },
  {
    id: 'search-73',
    name: 'Sculptra Filler',
    quantity: 34,
    category: '필러/보톡스/실',
    recentInboundDate: '2025.08.28',
    expirationDate: '26.06.30',
    isFavorite: false,
  },
  {
    id: 'search-74',
    name: 'Peptide Serum',
    quantity: 567,
    category: '화장품',
    recentInboundDate: '2025.06.22',
    expirationDate: '26.02.28',
    isFavorite: true,
  },
  {
    id: 'search-75',
    name: 'Bleomycin Injection',
    quantity: 123,
    category: '주사제',
    recentInboundDate: '2025.08.11',
    expirationDate: '25.11.15',
    isFavorite: false,
  },
  {
    id: 'search-76',
    name: 'Gauze Pad',
    quantity: 890,
    category: '소모품',
    recentInboundDate: '2025.07.28',
    expirationDate: '27.07.20',
    isFavorite: true,
  },
  {
    id: 'search-77',
    name: 'Radiesse Filler',
    quantity: 56,
    category: '필러/보톡스/실',
    recentInboundDate: '2025.08.23',
    expirationDate: '26.03.15',
    isFavorite: false,
  },
  {
    id: 'search-78',
    name: 'Hyaluronic Serum',
    quantity: 432,
    category: '화장품',
    recentInboundDate: '2025.07.15',
    expirationDate: '26.09.10',
    isFavorite: true,
  },
  {
    id: 'search-79',
    name: 'Dexamethasone Injection',
    quantity: 267,
    category: '주사제',
    recentInboundDate: '2025.08.09',
    expirationDate: '25.10.25',
    isFavorite: false,
  },
  {
    id: 'search-80',
    name: 'Bandage Tape',
    quantity: 750,
    category: '소모품',
    recentInboundDate: '2025.08.02',
    expirationDate: '27.02.28',
    isFavorite: true,
  },
  {
    id: 'search-81',
    name: 'Belotero Balance',
    quantity: 23,
    category: '필러/보톡스/실',
    recentInboundDate: '2025.08.29',
    expirationDate: '26.07.15',
    isFavorite: false,
  },
  {
    id: 'search-82',
    name: 'Ceramide Cream',
    quantity: 634,
    category: '화장품',
    recentInboundDate: '2025.06.28',
    expirationDate: '26.04.30',
    isFavorite: true,
  },
  {
    id: 'search-83',
    name: 'Tranexamic Injection',
    quantity: 145,
    category: '주사제',
    recentInboundDate: '2025.08.16',
    expirationDate: '25.12.05',
    isFavorite: false,
  },
  {
    id: 'search-84',
    name: 'Sterile Gloves',
    quantity: 600,
    category: '소모품',
    recentInboundDate: '2025.07.30',
    expirationDate: '27.08.31',
    isFavorite: true,
  },
  {
    id: 'search-85',
    name: 'Voluma Filler',
    quantity: 41,
    category: '필러/보톡스/실',
    recentInboundDate: '2025.08.26',
    expirationDate: '26.01.25',
    isFavorite: false,
  },
  {
    id: 'search-86',
    name: 'AHA BHA Toner',
    quantity: 512,
    category: '화장품',
    recentInboundDate: '2025.07.05',
    expirationDate: '26.05.15',
    isFavorite: true,
  },
  {
    id: 'search-87',
    name: 'Mesotherapy Solution',
    quantity: 189,
    category: '주사제',
    recentInboundDate: '2025.08.13',
    expirationDate: '25.11.10',
    isFavorite: false,
  },
  {
    id: 'search-88',
    name: 'Surgical Drape',
    quantity: 320,
    category: '소모품',
    recentInboundDate: '2025.08.07',
    expirationDate: '27.03.20',
    isFavorite: true,
  },
  {
    id: 'search-89',
    name: 'Teosyal Filler',
    quantity: 67,
    category: '필러/보톡스/실',
    recentInboundDate: '2025.08.24',
    expirationDate: '26.06.10',
    isFavorite: false,
  },
  {
    id: 'search-90',
    name: 'Snail Mucin Essence',
    quantity: 478,
    category: '화장품',
    recentInboundDate: '2025.07.18',
    expirationDate: '26.10.20',
    isFavorite: true,
  },
  {
    id: 'search-91',
    name: 'PRP Injection Kit',
    quantity: 98,
    category: '주사제',
    recentInboundDate: '2025.08.21',
    expirationDate: '26.02.05',
    isFavorite: false,
  },
  {
    id: 'search-92',
    name: 'Medical Tape',
    quantity: 1100,
    category: '소모품',
    recentInboundDate: '2025.07.12',
    expirationDate: '27.09.15',
    isFavorite: true,
  },
  {
    id: 'search-93',
    name: 'Ellanse Filler',
    quantity: 29,
    category: '필러/보톡스/실',
    recentInboundDate: '2025.08.30',
    expirationDate: '26.08.25',
    isFavorite: false,
  },
  {
    id: 'search-94',
    name: 'Vitamin E Oil',
    quantity: 356,
    category: '화장품',
    recentInboundDate: '2025.06.15',
    expirationDate: '26.03.10',
    isFavorite: true,
  },
  {
    id: 'search-95',
    name: 'Hyaluronidase Injection',
    quantity: 201,
    category: '주사제',
    recentInboundDate: '2025.08.17',
    expirationDate: '25.10.05',
    isFavorite: false,
  },
  {
    id: 'search-96',
    name: 'Disposable Cap',
    quantity: 950,
    category: '소모품',
    recentInboundDate: '2025.08.04',
    expirationDate: '27.10.30',
    isFavorite: true,
  },
  {
    id: 'search-97',
    name: 'Revanesse Filler',
    quantity: 52,
    category: '필러/보톡스/실',
    recentInboundDate: '2025.08.27',
    expirationDate: '26.04.20',
    isFavorite: false,
  },
  {
    id: 'search-98',
    name: 'Coenzyme Q10 Cream',
    quantity: 423,
    category: '화장품',
    recentInboundDate: '2025.07.22',
    expirationDate: '26.07.30',
    isFavorite: true,
  },
  {
    id: 'search-99',
    name: 'Polynucleotide Injection',
    quantity: 167,
    category: '주사제',
    recentInboundDate: '2025.08.15',
    expirationDate: '25.12.20',
    isFavorite: false,
  },
  {
    id: 'search-100',
    name: 'Surgical Scissors',
    quantity: 45,
    category: '소모품',
    recentInboundDate: '2025.08.31',
    expirationDate: '27.11.15',
    isFavorite: true,
  },
];